# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### 获取用户列表
GET http://localhost:3333/user
Accept: application/json

###

### 创建用户
POST http://localhost:3333/user
Content-Type: application/json

{
  "name": "大名"
}

###

### 修改一个用户名称
PUT http://localhost:3333/user/1
Content-Type: application/json

{
  "name": "修改名字"
}

###

### 删除一个用户
DELETE http://localhost:3333/user/1
Content-Type: application/json

###
